version: 2
project_name: supa-emu

before:
  hooks:
    - go mod tidy

builds:
  - id: supa-emu
    main: ./
    binary: supa-emu
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: supa-emu
    ids: [supa-emu]
    formats: [tar.gz]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE*
      - README*

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude: ['^docs:', '^test:', '^chore:', 'Merge pull request', 'Merge branch']

release:
  draft: false
  prerelease: auto
